language: python
python:
  - "2.7"
env:
  - FLASK=0.10.1
install:
  - pip install -q flask==$FLASK --use-mirrors
  - pip install -r requirements.txt
script:
  - flake8 client
notifications:
  slack: fydpsaavy:haAycUdAeGxxztOPa095IpHl