language: python
python:
  - "2.7"
env:
  - FLASK=0.10.1
install:
  - ./install.sh
script:
  - ./build.sh
after_success:
  - codecov
services:
  - redis-server
notifications:
  slack: fydpsaavy:haAycUdAeGxxztOPa095IpHl